name: App

env:
  AZURE_WEBAPP_NAME: github-actions-fme-bu4
  BUILD_DIR: app # set this to the name of your Azure Web App
  PYTHON_VERSION: "3.9" # set this to the Python version to use
  APP_SETTINGS: '[{"name": "DEBUG", "value": "True"}]' # set this to the settings to use

on:
  push:
    branches:
      - "develop"
    paths:
      - "app/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    environment:
      name: dev-app
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    defaults:
      run:
        working-directory: ${{ env.BUILD_DIR }}

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set app settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: "${{ env.AZURE_WEBAPP_NAME }}"
          app-settings-json: "${{ env.APP_SETTINGS }}"

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.BUILD_DIR }}
